version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "3000:3000"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: api-devices
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/devicesdb

volumes:
  mongo-data:
